from listas import LinKedList
from tarea_7 import ListaDoble
l=LinKedList()
l.append(10)
l.append(5)
l.append(6)
l.append(5)
l.append(34)
l.append(67)
l.append(56)
print(f"l esta vacia? {l.is_empty()}" )
l.trasversal()
l.remove(10)
l.trasversal()
l.preppend(2)
l.trasversal()
x = l.tail()
print(x.data)
s=l.get(56)
print("#######################################3")
print(s)
print("#######################################3")
f=ListaDoble()
print(f"f esta vacia? {f.is_empty()}" )
f.append(4)
f.append(3)
f.append(2)
f.append(44)
f.append(43)
f.trasversal()
print(f"f esta vacia? {f.is_empty()}" )
print("#######################################3")

j=f.get_size()
print(j)
print("#######################################3")

f.reverse_trasversal()
print("#######################################3")

c=f.find_from_head(4)
print(c.data)
f.remove_tail(44)
f.trasversal()
print("#######################################3")
f.reverse_trasversal()
print("#######################################3")
